config/routes.rb
Rails.application.routes.draw do
  resources :cars
  devise_for :users
  resources :friends
  root 'home#index'
  get "home/about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :user
	validates :engine, :drivetrain, presence: true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
	validates :email, presence: true
	validates :phone, :numericality => {:only_integer => true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends

         has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = current_user.cars.build
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = current_user.cars.build(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @car = current_user.cars.find_by(id: params[:id])
    redirect_to cars_path, notice: "Not authorized to edit this car" if @car.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :engine, :drivetrain)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
   #@friend = Friend.new
   @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :birthday, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :make %>
    <%= form.text_field :make, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :model %>
    <%= form.text_field :model, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :year %>
    <%= form.text_field :year, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :engine %>
    <%= form.text_field :engine, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :drivetrain %>
    <%= form.text_field :drivetrain, class:"form-control" %>
  </div>

  <!--
  <div class="field mb-3">
    <%= form.number_field :user_id, id: :car_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
-->
  
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>


<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>
</br>

<%= link_to 'Show', @car, class:"btn btn-secondary" %>
<%= link_to 'Back', cars_path, class:"btn btn-secondary" %>

app/views/cars/index.html.erb
<h1>Cars</h1>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Engine</th>
      <th>Drivetrain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
    <% if car.user == current_user %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.engine %></td>
        <td><%= car.drivetrain %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path, class:"btn btn-secondary" %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

</br>
<%= link_to 'Back', cars_path, class:"btn btn-secondary" %>

app/views/cars/show.html.erb
<table>
  <tr>
    <p>
      <strong>Make:</strong>
      <%= @car.make %>
    </p>
  </tr>

  <tr>
    <p>
      <strong>Model:</strong>
      <%= @car.model %>
    </p>
  </tr>

  <tr>
    <p>
      <strong>Year:</strong>
      <%= @car.year %>
    </p>
  </tr>

  <tr>
    <p>
      <strong>Engine:</strong>
      <%= @car.engine %>
    </p>
  </tr>

  <tr>
    <p>
      <strong>Drivetrain:</strong>
      <%= @car.drivetrain %>
    </p>
  </tr>
</table>

<%= link_to 'Edit', edit_car_path(@car), class:"btn btn-secondary" %>
<%= link_to 'Back', cars_path, class:"btn btn-secondary" %>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <!--
  <div class="field mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  -->

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing a Friend</h1>

<%= render 'form', friend: @friend %>
</br>

<%= link_to 'Show', @friend, class:"btn btn-secondary"%>
<%= link_to 'Back', friends_path, class:"btn btn-secondary"%>

app/views/friends/index.html.erb
<h1>Friends</h1>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthday</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.birthday %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary"%>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

</br>
<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/friends/show.html.erb
<table>
  <tr>
    <p>
     <td><strong>First name:</strong></td>
     <td><%= @friend.first_name %></td>
    </p>
  </tr>

  <tr>
    <p>
      <td><strong>Last name:</strong></td>
      <td><%= @friend.last_name %></td>
    </p>
  </tr>

  <tr>
    <p>
      <td><strong>Birthday:</strong></td>
      <td><%= @friend.birthday %></td>
    </p>
  </tr>

  <tr>
    <p>
      <td><strong>Email:</strong></td>
      <td><%= @friend.email %></td>
    </p>
  </tr>

  <tr>
    <p>
      <td><strong>Phone:</strong></td>
      <td><%= @friend.phone %></td>
    </p>
  </tr>
</table>

<%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>
<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to "Friends App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        
        

        <!--Devise-->
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Friends", friends_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Cars", cars_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "New Friend", new_friend_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Add Car", new_car_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>
<p> My name is Radim Novák. I was born on 24th November, 2000 in Prague, Czech Republic</p>
<p> My main hobbies are cars and computer science</p>
<p> I drive a lovely 328i E36 BMW and I am currently in the process of learning ruby on rails, therefore I created this page</p>

app/views/home/index.html.erb
<h1>Hello World!!</h1>
<p>This is my new webpage containing my Friends app, Cars app and my journey with Ruby on Rails</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>FriendsApp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= render "home/navbar" %>
    <div class="container">
      <%if notice %>
        <%= render "layouts/alerts" %>
      <% end %>
    <%= yield %>
    </div>

  <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>